# Generated by Django 5.1.1 on 2024-09-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
