# Generated by Django 5.1.1 on 2024-09-12 14:40

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='default_name', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 14, 38, 54, 15355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
