# Generated by Django 5.1.1 on 2024-09-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_trial_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 12, 13, 29, 28191, tzinfo=datetime.timezone.utc)),
        ),
    ]
