# Generated by Django 5.1.1 on 2024-09-15 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_username_alter_profile_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 16, 57, 30, 75885, tzinfo=datetime.timezone.utc)),
        ),
    ]
