# Generated by Django 5.1.1 on 2024-09-22 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_profile_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 22, 2, 848111, tzinfo=datetime.timezone.utc)),
        ),
    ]
