# Generated by Django 5.1.1 on 2024-09-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_profile_trial_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trial_end_date',
        ),
    ]
