# Generated by Django 5.1.1 on 2024-09-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
