# Generated by Django 5.1.1 on 2024-09-24 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_delete_book'),
        ('subscriptions', '0002_alter_subscription_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookpurchase',
            unique_together={('user', 'book')},
        ),
    ]
